user_home_dir: /home/mmbl
repo: "{{ user_home_dir }}/repo"
_user: mmbl
_group: mmbl
# связанные параметры, для удобства восприятия
# выделен параметр для явного указания JAVA_HOME
_files_jdk: "jdk-8u241-linux-x64.tar.gz"
_java_version: "1.8.0_241"
# =============== #
_files_fmw: "fmw_12.1.3.0.0_wls.jar"

# Для реализации WLS
oracle_base: "{{ user_home_dir }}/oracle"
JAVA_HOME: "{{ user_home_dir }}/jdk{{ _java_version }}"
MW_HOME: "{{ oracle_base }}/middleware1213"
weblogic_home: '{{ MW_HOME }}/wlserver'
mw_installer_folder: '{{ MW_HOME }}/install'
domains_home: "{{ MW_HOME }}/user_projects/domains"
# ====================== #